### ISSUE TITLE
IconSupport for A12

### ISSUE THREAD

**Issue by t0mi** [Xuzz/IconSupport#4]
[iconsupport a12.zip](https://github.com/grp/IconSupport/files/3264501/iconsupport.a12.zip)

**Comment by ashikase** [comment]
Can you please post the changes that you made to the source in order to compile, as well the tools that you used (theos version, Xcode version, iOS SDK version, etc.)?

**Comment by t0mi** [comment]
I'm not a developer or anything like that, so I do not know that much.  We just added an arm64e slice using Xcode 10.1.  The result was successfully tested on several devices.
